version: '3.3'
services:
 my-nginx:
  image: nginx:latest
  volumes:
   - ./volume/default.conf:/etc/nginx/conf.d/default.conf
   - ./volume:/etc/nginx/test
  ports:
   - 80:80
  restart: always
  container_name: my-nginx

 my-tomcat:
  image: tomcat:latest
  expose:
   - 8080
  restart: always
  container_name: my-tomcat